language: node_js
node_js:
  - lts/*
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE langmatetest;" -U postgres
  - psql -c "CREATE USER langmatetest WITH PASSWORD '123';" -U postgres
  - psql -c "ALTER DATABASE langmatetest OWNER TO langmatetest;" -U postgres